services:
  database:
    container_name: postgres_rugby_manager
    image: 'postgres:17.7'
    environment:
      - POSTGRES_DB=RUGBY_DB
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Azerty,123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - rugby_network

  pgadmin:
    container_name: pgadmin_rugby_manager
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=Azerty,123
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - rugby_network
    depends_on:
      - database

volumes:
  postgres_data:
  pgadmin_data:

networks:
  rugby_network:
    driver: bridge
