spring:
  application:
    name: RugbyManager
  datasource:
    url: jdbc:postgresql://localhost:5433/RUGBY_DB
    username: admin
    password: Azerty,123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  messages:
    encoding: UTF-8

app:
  jwt:
    secret: 2437405c593346403d2b3d33483d70514f40754665547d416145485b3b
